import "server-only";

import QRCode from "qrcode";
import type { ShipmentRequest } from "./types";

function escapePdf(value: string) {
  return value
    .replace(/[^\x20-\x7e]/g, "?")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function pdfText(font: "F1" | "F2", size: number, x: number, y: number, value: string) {
  return "BT /" + font + " " + size + " Tf " + x + " " + y + " Td (" + escapePdf(value) + ") Tj ET";
}

function wrapText(value: string, maxLength: number) {
  const words = value.trim().split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (line && line.length + word.length + 1 > maxLength) {
      lines.push(line);
      line = word;
    } else {
      line = line ? line + " " + word : word;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

function qrDrawing(value: string, x: number, y: number, size: number) {
  // The matrix is generated locally, so tracking data is never sent to a
  // third-party QR service before the label is printed.
  const matrix = QRCode.create(value, { errorCorrectionLevel: "M" }).modules;
  const modules = matrix.size;
  const unit = size / modules;
  const operations = ["0 g"];
  for (let row = 0; row < modules; row += 1) {
    for (let column = 0; column < modules; column += 1) {
      if (matrix.data[row * modules + column]) {
        operations.push(
          unit.toFixed(3) + " 0 0 " + unit.toFixed(3) + " "
          + (x + column * unit).toFixed(3) + " "
          + (y + (modules - row - 1) * unit).toFixed(3) + " re f",
        );
      }
    }
  }
  return operations.join("\n");
}

/** A professional printable 4x6in AWB label for manual and sandbox dispatch. */
export function createProfessionalThermalLabelPdf(
  input: ShipmentRequest,
  carrierName: string,
  trackingNumber: string,
) {
  const recipientAddress = [
    ...wrapText(input.shippingAddress, 32),
    ...wrapText([input.shippingCity, input.shippingPostcode].filter(Boolean).join(" "), 32),
  ];
  const senderAddress = wrapText(input.senderAddress || "Warehouse dispatch", 28);
  const dimensions = input.lengthCm && input.widthCm && input.heightCm
    ? input.lengthCm + " x " + input.widthCm + " x " + input.heightCm + " cm"
    : "Dimensions not declared";
  const qrValue = "AWB:" + trackingNumber + "|SO:" + input.orderNumber;
  const content = [
    "q 0.055 0.102 0.18 rg 0 360 288 72 re f Q",
    "0.82 G 0.8 w 18 24 252 318 re S",
    "0.82 G 0.5 w 18 190 m 270 190 l S",
    "0.82 G 0.5 w 18 104 m 270 104 l S",
    "1 1 1 rg",
    pdfText("F2", 17, 28, 402, input.senderName || "ProConnect WMS"),
    pdfText("F1", 8, 28, 387, "WAREHOUSE MANAGEMENT SYSTEM"),
    pdfText("F2", 10, 28, 370, "SHIPMENT / AIR WAYBILL"),
    "0 g",
    pdfText("F2", 8, 28, 342, "FROM"),
    pdfText("F1", 9, 28, 329, input.senderName || "ProConnect WMS"),
    ...senderAddress.slice(0, 2).map((line, index) => pdfText("F1", 8, 28, 316 - index * 11, line)),
    pdfText("F2", 8, 28, 283, "TO / CONSIGNEE"),
    pdfText("F2", 12, 28, 267, input.customerName),
    ...recipientAddress.slice(0, 4).map((line, index) => pdfText("F1", 9, 28, 253 - index * 12, line)),
    qrDrawing(qrValue, 184, 231, 76),
    pdfText("F2", 7, 184, 219, "SCAN AWB"),
    pdfText("F2", 12, 28, 174, "AWB  " + trackingNumber),
    pdfText("F1", 9, 28, 158, "SALES ORDER  " + input.orderNumber),
    pdfText("F1", 9, 28, 142, "CARRIER  " + carrierName),
    pdfText("F1", 9, 28, 126, "SERVICE  " + (input.serviceCode || "STANDARD")),
    pdfText("F2", 8, 28, 84, "PARCEL DETAILS"),
    pdfText("F1", 9, 28, 69, "ITEMS: " + input.itemCount + "    WEIGHT: " + input.weightKg.toFixed(2) + " kg"),
    pdfText("F1", 9, 28, 55, "SIZE: " + dimensions),
    pdfText("F1", 7, 28, 36, "Generated by ProConnect WMS. Verify carrier service before handover."),
  ].join("\n");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 288 432] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    "<< /Length " + Buffer.byteLength(content, "utf8") + " >>\nstream\n" + content + "\nendstream",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  for (let index = 0; index < objects.length; index += 1) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += String(index + 1) + " 0 obj\n" + objects[index] + "\nendobj\n";
  }
  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += "xref\n0 " + (objects.length + 1) + "\n0000000000 65535 f \n";
  pdf += offsets.slice(1).map((offset) => String(offset).padStart(10, "0") + " 00000 n \n").join("");
  pdf += "trailer\n<< /Size " + (objects.length + 1) + " /Root 1 0 R >>\nstartxref\n" + xrefOffset + "\n%%EOF";
  return Buffer.from(pdf, "utf8").toString("base64");
}
