"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Check, ClipboardCheck, PackageX, RotateCcw, Truck } from "lucide-react";

type Product={id:string;sku:string;name:string}; type Location={id:string;location_code:string;display_code?:string}; type Po={id:string;po_number:string;purchase_order_items:any[]}; type So={id:string;order_number:string;order_items:any[]};
export function ExceptionConsole({orgId,products,locations,purchaseOrders,salesOrders}:{orgId:string;products:Product[];locations:Location[];purchaseOrders:Po[];salesOrders:So[]}){
 const [data,setData]=useState<any>({mispicks:[],rtvs:[],rmas:[],cycleCounts:[]}); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
 const [poId,setPoId]=useState(""); const [poLine,setPoLine]=useState(""); const [receiptQty,setReceiptQty]=useState("1"); const [receiptDisposition,setReceiptDisposition]=useState("AVAILABLE");
 const [soId,setSoId]=useState(""); const [soLine,setSoLine]=useState(""); const [shipQty,setShipQty]=useState("1");
 const [productId,setProductId]=useState(""); const [locationId,setLocationId]=useState(""); const [qty,setQty]=useState("1"); const [reason,setReason]=useState("DAMAGED"); const [supplier,setSupplier]=useState(""); const [customer,setCustomer]=useState("");
 const po=useMemo(()=>purchaseOrders.find(x=>x.id===poId),[purchaseOrders,poId]); const so=useMemo(()=>salesOrders.find(x=>x.id===soId),[salesOrders,soId]);
 async function load(){try{const r=await fetch(`/api/exceptions?orgId=${encodeURIComponent(orgId)}`);const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}catch(e){setMsg(e instanceof Error?e.message:"Unable to load exceptions.")}} useEffect(()=>{void load()},[orgId]);
 async function submit(action:string,payload:any,event?:FormEvent){event?.preventDefault();setBusy(true);setMsg("");try{const r=await fetch("/api/exceptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orgId,action,...payload})});const j=await r.json();if(!r.ok)throw new Error(j.error);setMsg("Saved successfully.");await load()}catch(e){setMsg(e instanceof Error?e.message:"Unable to save.")}finally{setBusy(false)}}
 const options=<><option value="">Select SKU…</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</>; const bins=<><option value="">Select bin…</option>{locations.map(l=><option key={l.id} value={l.id}>{l.display_code??l.location_code}</option>)}</>;
 return <div className="space-y-6">{msg&&<p role="alert" className="text-sm text-alert">{msg}</p>}<div className="grid gap-5 xl:grid-cols-2">
 <form onSubmit={e=>void submit("partialReceipt",{orderId:poId,receipts:[{purchaseOrderItemId:poLine,quantity:Number(receiptQty),disposition:receiptDisposition}]},e)} className="rounded-lg border border-line bg-panel p-5"><div className="flex gap-2"><Truck className="text-rack"/><div><h2 className="font-semibold">Partial PO receipt</h2><p className="text-xs text-graphite">Receive available or quarantine stock; the PO remains open.</p></div></div><div className="mt-4 grid gap-3"><select required value={poId} onChange={e=>{setPoId(e.target.value);setPoLine("")}} className="input-field"><option value="">Select pending PO…</option>{purchaseOrders.map(x=><option key={x.id} value={x.id}>{x.po_number}</option>)}</select><select required value={poLine} onChange={e=>setPoLine(e.target.value)} className="input-field"><option value="">Select PO line…</option>{(po?.purchase_order_items??[]).map((x:any)=><option key={x.id} value={x.id}>{x.products?.sku??"SKU"} · remaining {x.quantity_expected-x.quantity_received}</option>)}</select><div className="grid grid-cols-2 gap-3"><input required type="number" min="1" value={receiptQty} onChange={e=>setReceiptQty(e.target.value)} className="input-field"/><select value={receiptDisposition} onChange={e=>setReceiptDisposition(e.target.value)} className="input-field"><option value="AVAILABLE">Available stock</option><option value="QUARANTINE">Damaged → quarantine</option></select></div></div><button disabled={busy} className="btn-primary mt-4">Receive partial quantity</button></form>
 <form onSubmit={e=>void submit("partialShip",{orderId:soId,lines:[{orderItemId:soLine,quantity:Number(shipQty)}]},e)} className="rounded-lg border border-line bg-panel p-5"><div className="flex gap-2"><PackageX className="text-amber-dark"/><div><h2 className="font-semibold">Partial SO shipment</h2><p className="text-xs text-graphite">Ships an allocated non-serialized line and marks remaining stock as backordered.</p></div></div><div className="mt-4 grid gap-3"><select required value={soId} onChange={e=>{setSoId(e.target.value);setSoLine("")}} className="input-field"><option value="">Select allocated SO…</option>{salesOrders.map(x=><option key={x.id} value={x.id}>{x.order_number}</option>)}</select><select required value={soLine} onChange={e=>setSoLine(e.target.value)} className="input-field"><option value="">Select SO line…</option>{(so?.order_items??[]).map((x:any)=><option key={x.id} value={x.id}>{x.products?.sku??"SKU"} · reserved {x.quantity_reserved}</option>)}</select><input required type="number" min="1" value={shipQty} onChange={e=>setShipQty(e.target.value)} className="input-field"/></div><button disabled={busy} className="btn-primary mt-4">Ship available quantity</button></form>
 <form onSubmit={e=>void submit("createRtv",{supplierName:supplier,lines:[{productId,locationId,quantity:Number(qty),reason}]},e)} className="rounded-lg border border-line bg-panel p-5"><div className="flex gap-2"><RotateCcw className="text-alert"/><div><h2 className="font-semibold">Return to Vendor</h2><p className="text-xs text-graphite">Creates an RTV from quarantined stock; dispatch deducts only quarantined quantity.</p></div></div><div className="mt-4 grid gap-3"><input required placeholder="Supplier" value={supplier} onChange={e=>setSupplier(e.target.value)} className="input-field"/><select required value={productId} onChange={e=>setProductId(e.target.value)} className="input-field">{options}</select><select required value={locationId} onChange={e=>setLocationId(e.target.value)} className="input-field">{bins}</select><input required placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)} className="input-field"/><input required type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)} className="input-field"/></div><button disabled={busy} className="btn-danger mt-4">Create RTV</button></form>
 <form onSubmit={e=>void submit("createRma",{customerName:customer,lines:[{productId,locationId,quantity:Number(qty),disposition:"QUARANTINE",reason}]},e)} className="rounded-lg border border-line bg-panel p-5"><div className="flex gap-2"><RotateCcw className="text-violet-700"/><div><h2 className="font-semibold">Damaged customer return (RMA)</h2><p className="text-xs text-graphite">Returned stock enters quarantine, never available picking stock.</p></div></div><div className="mt-4 grid gap-3"><input placeholder="Customer (optional)" value={customer} onChange={e=>setCustomer(e.target.value)} className="input-field"/><select required value={productId} onChange={e=>setProductId(e.target.value)} className="input-field">{options}</select><select required value={locationId} onChange={e=>setLocationId(e.target.value)} className="input-field">{bins}</select><input required placeholder="Damage reason" value={reason} onChange={e=>setReason(e.target.value)} className="input-field"/><input required type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)} className="input-field"/></div><button disabled={busy} className="btn-primary mt-4">Receive damaged return</button></form>
 <form onSubmit={e=>void submit("submitCycleCount",{lines:[{productId,locationId,physicalQuantity:Number(qty),reasonCode:reason}]},e)} className="rounded-lg border border-line bg-panel p-5 xl:col-span-2"><div className="flex gap-2"><ClipboardCheck className="text-go"/><div><h2 className="font-semibold">Blind cycle count</h2><p className="text-xs text-graphite">System quantity remains hidden from the entry workflow. Discrepancies require a reason and manager approval before balances change.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-4"><select required value={productId} onChange={e=>setProductId(e.target.value)} className="input-field">{options}</select><select required value={locationId} onChange={e=>setLocationId(e.target.value)} className="input-field">{bins}</select><input required type="number" min="0" placeholder="Physical count" value={qty} onChange={e=>setQty(e.target.value)} className="input-field"/><select value={reason} onChange={e=>setReason(e.target.value)} className="input-field"><option>DAMAGED</option><option>MISSING</option><option>MISPLACED</option><option>COUNT_ERROR</option><option>OTHER</option></select></div><button disabled={busy} className="btn-primary mt-4">Submit for approval</button></form></div>
 <section className="rounded-lg border border-line bg-panel p-5"><h2 className="font-semibold">Pending reconciliation</h2><div className="mt-3 space-y-2">{(data.cycleCounts??[]).filter((c:any)=>c.status==="PENDING_APPROVAL").map((c:any)=><div key={c.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-line py-3"><span className="code-label">{c.count_number}</span><span className="text-sm text-graphite">{(c.cycle_count_items??[]).length} counted bin(s)</span><div className="flex gap-2"><button disabled={busy} onClick={()=>void submit("approveCycleCount",{cycleCountId:c.id,approve:false})} className="btn-secondary">Reject</button><button disabled={busy} onClick={()=>void submit("approveCycleCount",{cycleCountId:c.id,approve:true})} className="btn-primary"><Check size={15}/>Approve adjustment</button></div></div>)}{!(data.cycleCounts??[]).some((c:any)=>c.status==="PENDING_APPROVAL")&&<p className="py-3 text-sm text-graphite">No pending cycle-count approvals.</p>}</div></section>
 <section className="rounded-lg border border-line bg-panel p-5"><h2 className="font-semibold">Recent mispick attempts</h2><div className="mt-3 space-y-2">{(data.mispicks??[]).map((m:any)=><div key={m.id} className="flex justify-between gap-3 border-t border-line py-2 text-sm"><span className="code-label">{m.scanned_value}</span><span className="text-alert">{m.reason_code}</span><span className="text-graphite">{new Date(m.created_at).toLocaleString()}</span></div>)}{!(data.mispicks??[]).length&&<p className="py-3 text-sm text-graphite">No mispick attempts recorded.</p>}</div></section></div>
}
