"use client";

import { Package } from "lucide-react";
import { RowActions } from "@/components/ui/RowActions";
import { StatusBadge } from "@/components/ui/StatusBadge";

type Row = { id: string; sku: string; barcode: string; name: string; unit_of_measure: string; onHand: number; reserved: number; locations: number };
export function InventoryTable({ rows, canManage }: { rows: Row[]; canManage: boolean }) {
  return <div className="mt-6 overflow-hidden rounded-lg border border-line bg-panel"><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-sm"><thead className="sticky top-0 z-10 bg-paper text-left text-[11px] uppercase tracking-wide text-graphite"><tr><th className="px-5 py-3">Product</th><th className="px-5 py-3">SKU / barcode</th><th className="px-5 py-3 text-right">On hand</th><th className="px-5 py-3 text-right">Reserved</th><th className="px-5 py-3 text-right">Available</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"/></tr></thead><tbody>{rows.map(row => { const available = row.onHand - row.reserved; const low = available < 5; return <tr key={row.id} className="border-t border-line transition hover:bg-paper/70"><td className="px-5 py-3"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-rack/10 text-rack"><Package size={18}/></span><span className="font-medium">{row.name}</span></div></td><td className="px-5 py-3"><div className="code-label text-xs">{row.sku}</div><div className="code-label mt-1 text-xs text-graphite">{row.barcode}</div></td><td className="px-5 py-3 text-right font-medium">{row.onHand} {row.unit_of_measure}</td><td className="px-5 py-3 text-right text-graphite">{row.reserved}</td><td className={`px-5 py-3 text-right font-semibold ${low ? "text-alert" : "text-go"}`}>{available}</td><td className="px-5 py-3">{low ? <StatusBadge status="LOW"/> : <StatusBadge status="ACTIVE"/>}</td><td className="px-5 py-3"><RowActions onView={() => {}} onEdit={canManage ? () => {} : undefined} onDuplicate={canManage ? () => {} : undefined} onDelete={canManage ? () => {} : undefined}/></td></tr>; })}</tbody></table></div><div className="border-t border-line px-5 py-3 text-sm text-graphite">{rows.length} SKU records · pagination ready</div></div>;
}
