"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Warehouse={id:string;code:string;name:string;warehouse_zones:{id:string;zone_code:string;zone_type:string}[]};
export function LocationManager({orgId,canManage,warehouses}:{orgId:string;canManage:boolean;warehouses:Warehouse[]}){
 const supabase=createClient();const[msg,setMsg]=useState("");if(!canManage)return null;
 async function createWarehouse(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await(supabase.from("warehouses")as any).insert({org_id:orgId,code:f.get("code"),name:f.get("name")});setMsg(error?error.message:"Warehouse created. Refresh Locations.");if(!error)e.currentTarget.reset();}
 async function createBin(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const zoneId=String(f.get("zoneId")||"");const{error}=await(supabase.from("locations")as any).insert({zone_id:zoneId,location_code:f.get("location"),aisle:f.get("aisle")||null,rack:f.get("rack")||null,shelf:f.get("shelf")||null,bin:f.get("bin")||null});setMsg(error?error.message:"Location created. Refresh Locations.");if(!error)e.currentTarget.reset();}
 const zones=warehouses.flatMap(w=>w.warehouse_zones.map(z=>({...z,warehouse:w.code})));
 return <div className="grid gap-4 md:grid-cols-2"><form onSubmit={createWarehouse} className="border border-line bg-panel p-4"><div className="mb-3 text-sm font-medium">Create warehouse</div><div className="flex gap-2"><input name="code" required placeholder="Code" className="w-28 border border-line bg-paper px-3 py-2 text-sm code-label"/><input name="name" required placeholder="Warehouse name" className="flex-1 border border-line bg-paper px-3 py-2 text-sm"/><button className="bg-ink px-3 text-sm text-white">Add</button></div></form><form onSubmit={createBin} className="border border-line bg-panel p-4"><div className="mb-3 text-sm font-medium">Create bin location</div><div className="grid grid-cols-2 gap-2"><select name="zoneId" required className="border border-line bg-paper px-3 py-2 text-sm"><option value="">Zone…</option>{zones.map(z=><option key={z.id} value={z.id}>{z.warehouse} · {z.zone_code}</option>)}</select><input name="location" required placeholder="A-01-01-A" className="border border-line bg-paper px-3 py-2 text-sm code-label"/><input name="aisle" placeholder="Aisle" className="border border-line bg-paper px-3 py-2 text-sm"/><input name="rack" placeholder="Rack" className="border border-line bg-paper px-3 py-2 text-sm"/><input name="shelf" placeholder="Shelf" className="border border-line bg-paper px-3 py-2 text-sm"/><input name="bin" placeholder="Bin" className="border border-line bg-paper px-3 py-2 text-sm"/></div><button className="mt-2 bg-ink px-3 py-2 text-sm text-white">Add location</button></form>{msg&&<p className="text-sm text-graphite md:col-span-2">{msg}</p>}</div>;
}
