"use client";
import { FormEvent, useState } from "react";
import { MapPinPlus } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { Drawer } from "@/components/ui/Drawer";
type Warehouse={id:string;code:string;name:string;warehouse_zones:{id:string;zone_code:string;zone_type:string}[]};
export function LocationManager({orgId,canManage,warehouses}:{orgId:string;canManage:boolean;warehouses:Warehouse[]}){
 const supabase=createClient();const[open,setOpen]=useState(false);const[mode,setMode]=useState<"warehouse"|"bin">("warehouse");const[msg,setMsg]=useState("");if(!canManage)return null;const zones=warehouses.flatMap(w=>w.warehouse_zones.map(z=>({...z,warehouse:w.code})));
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();try{const f=new FormData(e.currentTarget);let error:any;if(mode==="warehouse")({error}=await(supabase.from("warehouses")as any).insert({org_id:orgId,code:f.get("code"),name:f.get("name")}));else({error}=await(supabase.from("locations")as any).insert({zone_id:f.get("zoneId"),location_code:f.get("location"),aisle:f.get("aisle")||null,rack:f.get("rack")||null,shelf:f.get("shelf")||null,bin:f.get("bin")||null}));if(error)throw error;setMsg(`${mode==="warehouse"?"Warehouse":"Location"} created. Refresh Locations.`);e.currentTarget.reset();}catch(error){setMsg(error instanceof Error?error.message:"Unable to save this location.");}}
 return <><div className="flex justify-end"><button onClick={()=>setOpen(true)} className="btn-primary"><MapPinPlus size={16}/>Add location</button></div><Drawer open={open} onClose={()=>setOpen(false)} title={mode==="warehouse"?"Add warehouse":"Add bin location"} description="Maintain your warehouse hierarchy"><div className="mb-6 flex rounded-md bg-paper p-1"><button onClick={()=>setMode("warehouse")} className={`flex-1 rounded px-3 py-2 text-sm ${mode==="warehouse"?"bg-panel shadow-sm text-ink":"text-graphite"}`}>Warehouse</button><button onClick={()=>setMode("bin")} className={`flex-1 rounded px-3 py-2 text-sm ${mode==="bin"?"bg-panel shadow-sm text-ink":"text-graphite"}`}>Bin location</button></div><form onSubmit={save} className="space-y-4">{mode==="warehouse"?<><label className="block text-sm">Warehouse code<input name="code" required className="input-field mt-1 code-label"/></label><label className="block text-sm">Warehouse name<input name="name" required className="input-field mt-1"/></label></>:<><label className="block text-sm">Zone<select name="zoneId" required className="input-field mt-1"><option value="">Select zone…</option>{zones.map(z=><option key={z.id} value={z.id}>{z.warehouse} · {z.zone_code}</option>)}</select></label><label className="block text-sm">Bin location code<input name="location" required placeholder="A-01-01-A" className="input-field mt-1 code-label"/></label><div className="grid grid-cols-2 gap-3">{["aisle","rack","shelf","bin"].map(field=><label key={field} className="block text-sm capitalize">{field}<input name={field} className="input-field mt-1"/></label>)}</div></>}{msg&&<p className="text-sm text-graphite">{msg}</p>}<div className="flex justify-end gap-2 border-t border-line pt-5"><button type="button" onClick={()=>setOpen(false)} className="btn-secondary">Cancel</button><button className="btn-primary">Save</button></div></form></Drawer></>;
}
