"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Order={id:string;order_number:string;platform:string;customer_name:string|null;status:string;created_at:string};
const STATUSES=["NEW","ALLOCATED","PICKING","PACKED","SHIPPED"];
export function OrderManager({orgId,orgName,canManage,initialOrders}:{orgId:string;orgName:string;canManage:boolean;initialOrders:Order[]}){
 const supabase=createClient();const[orders,setOrders]=useState(initialOrders);const[msg,setMsg]=useState("");
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const{data,error}=await(supabase.from("sales_orders")as any).insert({org_id:orgId,order_number:f.get("number"),platform:f.get("platform"),customer_name:f.get("customer"),status:"NEW"}).select().single();if(error)return setMsg(error.message);setOrders(x=>[data,...x]);e.currentTarget.reset();}
 async function status(order:Order,next:string){const{error}=await(supabase.from("sales_orders")as any).update({status:next}).eq("id",order.id);if(error)return setMsg(error.message);setOrders(x=>x.map(o=>o.id===order.id?{...o,status:next}:o));}
 async function remove(id:string){const{error}=await(supabase.from("sales_orders")as any).delete().eq("id",id);if(error)return setMsg(error.message);setOrders(x=>x.filter(o=>o.id!==id));}
 return <div className="space-y-4">{canManage&&<form onSubmit={add} className="grid gap-2 border border-line bg-panel p-4 sm:grid-cols-4"><input name="number" required placeholder="Order number" className="border border-line bg-paper px-3 py-2 text-sm"/><input name="platform" defaultValue="MANUAL" className="border border-line bg-paper px-3 py-2 text-sm"/><input name="customer" placeholder="Customer" className="border border-line bg-paper px-3 py-2 text-sm"/><button className="bg-ink px-3 py-2 text-sm text-white">Create order</button></form>}{msg&&<p className="text-sm text-alert">{msg}</p>}<div className="border border-line bg-panel"><table className="w-full text-sm"><thead><tr className="border-b border-line text-left text-xs uppercase text-graphite"><th className="px-5 py-3">Order</th><th className="px-5 py-3">Organization</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Status</th>{canManage&&<th/>}</tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-b border-line"><td className="code-label px-5 py-3">{o.order_number}<div className="text-graphite">{o.platform}</div></td><td className="px-5 py-3"><span className="border border-rack/30 bg-rack/10 px-2 py-1 text-xs text-rack">{orgName}</span></td><td className="px-5 py-3">{o.customer_name??"—"}</td><td className="px-5 py-3">{canManage?<select value={o.status} onChange={e=>status(o,e.target.value)} className="border border-line bg-paper px-2 py-1">{STATUSES.map(s=><option key={s}>{s}</option>)}</select>:o.status}</td>{canManage&&<td className="px-5 py-3"><button onClick={()=>remove(o.id)} className="text-alert">Delete</button></td>}</tr>)}</tbody></table></div></div>;
}
