"use client";

import { FormEvent, useEffect, useState } from "react";
import { RowActions } from "@/components/ui/RowActions";

type Org = { id: string; code: string; name: string; slug: string; deployment_mode: string; org_members: { id: string; user_id: string; user_code?: string; role: string; email?: string; disabled?: boolean }[] };

export function PlatformAdmin() {
  const [orgs, setOrgs] = useState<Org[]>([]);
  const [notice, setNotice] = useState("Loading organizations…");
  const [busy, setBusy] = useState(false);

  async function api(path = "", init: RequestInit = {}) {
    const response = await fetch(`/api/admin${path}`, { ...init, headers: { "Content-Type": "application/json", ...(init.headers ?? {}) } });
    const result = await response.json();
    if (!response.ok) throw new Error(result.error ?? "Request failed.");
    return result;
  }
  async function load() { try { const result = await api(); setOrgs(result.organizations); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to load organizations."); } }
  useEffect(() => { load(); }, []);
  async function createOrg(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await api("", { method: "POST", body: JSON.stringify({ kind: "organization", name: form.get("name"), slug: form.get("slug"), deploymentMode: form.get("mode") }) }); event.currentTarget.reset(); await load(); setNotice("Organization created."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to create organization."); } finally { setBusy(false); } }
  async function createUser(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await api("", { method: "POST", body: JSON.stringify({ kind: "user", email: form.get("email"), password: form.get("password"), orgId: form.get("orgId"), role: form.get("role") }) }); event.currentTarget.reset(); await load(); setNotice("User created and assigned."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to create user."); } finally { setBusy(false); } }
  async function changeRole(memberId: string, role: string) { try { await api("", { method: "PATCH", body: JSON.stringify({ memberId, role }) }); await load(); setNotice("Role updated."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to change role."); } }
  async function resetPassword(userId: string) { const password = window.prompt("Enter a new temporary password (12+ characters with letters and numbers):"); if (!password) return; try { await api("", { method: "PATCH", body: JSON.stringify({ kind: "password", userId, password }) }); setNotice("Temporary password updated."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to reset password."); } }
  async function setDisabled(userId: string, disabled: boolean) { try { await api("", { method: "PATCH", body: JSON.stringify({ kind: "disable", userId, disabled }) }); await load(); setNotice(disabled ? "Account disabled." : "Account enabled."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to update account status."); } }
  async function unassign(memberId: string) { try { await api(`?memberId=${encodeURIComponent(memberId)}`, { method: "DELETE" }); await load(); setNotice("User unassigned from this organization."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to unassign user."); } }

  return <div className="max-w-4xl space-y-6">
    {notice && <div className="border border-amber/40 bg-amber/10 px-4 py-3 text-sm">{notice}</div>}
    <section className="border border-line bg-panel p-5"><h2 className="stencil text-xl">Create organization</h2><p className="mt-1 text-sm text-graphite">The system assigns the next <span className="code-label">ORG#</span> identifier automatically.</p><form onSubmit={createOrg} className="mt-4 grid gap-3 sm:grid-cols-3"><input name="name" required placeholder="Organization name" className="border border-line bg-paper px-3 py-2 text-sm" /><input name="slug" required placeholder="organization-slug" className="border border-line bg-paper px-3 py-2 text-sm code-label" /><select name="mode" className="border border-line bg-paper px-3 py-2 text-sm"><option value="managed">Managed SaaS</option><option value="client_managed">Client-managed</option></select><button disabled={busy} className="bg-ink px-4 py-2 text-sm font-medium text-white sm:col-span-3">Create organization</button></form></section>
    <section className="border border-line bg-panel p-5"><h2 className="stencil text-xl">Create user and assign access</h2><p className="mt-1 text-sm text-graphite">Creates the login account and assigns its organization and role.</p><form onSubmit={createUser} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="email" type="email" required placeholder="user@company.com" className="border border-line bg-paper px-3 py-2 text-sm" /><input name="password" type="password" minLength={12} required placeholder="Temporary password (12+ letters and numbers)" className="border border-line bg-paper px-3 py-2 text-sm" /><select name="orgId" required className="border border-line bg-paper px-3 py-2 text-sm"><option value="">Assign organization…</option>{orgs.map((org) => <option key={org.id} value={org.id}>{org.code} · {org.name}</option>)}</select><select name="role" className="border border-line bg-paper px-3 py-2 text-sm"><option value="operator">Operator</option><option value="manager">Manager</option><option value="owner">Owner</option></select><button disabled={busy || orgs.length === 0} className="bg-ink px-4 py-2 text-sm font-medium text-white sm:col-span-2">Create and assign user</button></form></section>
    <section className="overflow-hidden border border-line bg-panel"><div className="border-b border-line px-5 py-3 text-sm font-medium">Organizations and assigned users</div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-paper text-left text-[11px] uppercase tracking-wide text-graphite"><tr><th className="px-5 py-3">User</th><th className="px-5 py-3">Organization</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Actions</th></tr></thead><tbody>{orgs.flatMap(org=>org.org_members.map(member=><tr key={member.id} className="border-t border-line hover:bg-paper/70"><td className="px-5 py-3"><div className="code-label font-medium">{member.user_code ?? "USR?"}</div><div className="text-graphite">{member.email}</div></td><td className="px-5 py-3"><span className="code-label">{org.code}</span><span className="ml-2">{org.name}</span></td><td className="px-5 py-3"><select value={member.role} onChange={(event) => changeRole(member.id, event.target.value)} className="rounded-full border border-line bg-panel px-2.5 py-1 text-xs font-medium text-rack"><option value="operator">Operator</option><option value="manager">Manager</option><option value="owner">Owner</option></select></td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${member.disabled?"bg-slate-100 text-graphite":"bg-emerald-50 text-go"}`}>{member.disabled?"Inactive":"Active"}</span></td><td className="px-5 py-3"><RowActions extraActions={[{ label: "Reset password", onClick: () => resetPassword(member.user_id) }, { label: member.disabled ? "Enable account" : "Disable account", onClick: () => setDisabled(member.user_id, !member.disabled), destructive: !member.disabled }]} onDelete={() => unassign(member.id)} deleteLabel="Unassign" deleteTitle="Unassign this user?" deleteDescription="They will lose access to this organization, but their account remains available for other organizations." /></td></tr>))}</tbody></table></div></section>
  </div>;
}
