-- Automatic human-readable identifiers are generated by triggers. The trigger
-- functions must bypass RLS on the internal counter table, while application
-- users retain no direct counter-table write permission.

alter table public.identifier_sequences enable row level security;

create or replace function public.assign_organization_code()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_sequence integer;
begin
  if new.code is null or new.code !~ '^ORG[0-9]+$' then
    insert into public.identifier_sequences(entity, last_value) values ('organization', 1)
    on conflict (entity) do update set last_value = public.identifier_sequences.last_value + 1
    returning last_value into v_sequence;
    new.code := 'ORG' || v_sequence;
  end if;
  return new;
end;
$$;

create or replace function public.assign_location_display_code()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_sequence integer;
begin
  if new.display_code is null or new.display_code !~ '^LOC[0-9]+$' then
    insert into public.identifier_sequences(entity, last_value) values ('location', 1)
    on conflict (entity) do update set last_value = public.identifier_sequences.last_value + 1
    returning last_value into v_sequence;
    new.display_code := 'LOC' || v_sequence;
  end if;
  return new;
end;
$$;

create or replace function public.assign_product_sku()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_sequence integer;
begin
  if new.sku is null or new.sku !~ '^SKU[0-9]+$' then
    insert into public.identifier_sequences(entity, last_value) values ('sku', 1)
    on conflict (entity) do update set last_value = public.identifier_sequences.last_value + 1
    returning last_value into v_sequence;
    new.sku := 'SKU' || v_sequence;
  end if;
  return new;
end;
$$;
